##
#
# Agent <> Proposal query API
#
# Provides information about the relationships between agents and proposals.
# Allows flagging Proposals for interest by agents who have an interest in
# completing them.
#
# @package  vf-graphql
# @since    2022-04-12
#
##

type Proposal {
  """
  An agent to which the proposal is to be proposed.  A proposal can be proposed to many agents.
  """
  proposedTo: [Agent!]

  "Grouping around something to create a boundary or context, used for documenting, accounting, planning."
  inScopeOf: [AccountingScope!]
}

##
#  API call input and output types
##

input ProposalCreateParams {
  "(`AccountingScope`) Grouping around something to create a boundary or context, used for documenting, accounting, planning."
  inScopeOf: [ID!]
}

input ProposalUpdateParams {
  "(`AccountingScope`) Grouping around something to create a boundary or context, used for documenting, accounting, planning."
  inScopeOf: [ID!]
}

interface Agent {
  proposals(first: Int, after: String, last: Int, before: String): ProposalConnection
  proposalsInScope(first: Int, after: String, last: Int, before: String): ProposalConnection
  proposalsTo(first: Int, after: String, last: Int, before: String): ProposalConnection
}

type Person implements Agent {
  proposals(first: Int, after: String, last: Int, before: String): ProposalConnection
  proposalsInScope(first: Int, after: String, last: Int, before: String): ProposalConnection
  proposalsTo(first: Int, after: String, last: Int, before: String): ProposalConnection
}

type Organization implements Agent {
  proposals(first: Int, after: String, last: Int, before: String): ProposalConnection
  proposalsInScope(first: Int, after: String, last: Int, before: String): ProposalConnection
  proposalsTo(first: Int, after: String, last: Int, before: String): ProposalConnection
}