##
#
# Agent <> Plan API
#
# Provides information about the relationships between agents and plans.
#
# @package  vf-graphql
# @since    2020-02-11
#
##

type Plan {
  ##############################################################################
  # inverse relationships and queries

  "Grouping around something to create a boundary or context, used for documenting, accounting, planning."
  inScopeOf: [AccountingScope!]
}


"Query parameters for reading `Plan`s related to an `Agent`"
input agentPlanSearchParams {
  searchString: String
  finished: Boolean
}

interface Agent {
  plans(filter: agentPlanSearchParams): [Plan!]
}

type Person implements Agent {
  plans(filter: agentPlanSearchParams): [Plan!]
}

type Organization implements Agent {
  plans(filter: agentPlanSearchParams): [Plan!]
}
