##
#
# Observation <> Plan API
#
# Augments observation records with the ability to be referenced in Plans.
#
# @package  vf-graphql
# @since    2020-02-12
#
##

type Process {
  "The process with its inputs and outputs is part of the plan."
  plannedWithin: Plan
}

type Plan {
  processes(first: Int, after: String, last: Int, before: String): ProcessConnection!
}
