##
#
# Observation <> Process API
#
# Augments Observation records (EconomicEvent specifically) with the ability to reference Processes
# and vice versa.
#
# @package  vf-graphql
# @since    2022-05-27
#
##

union ProductionFlowItem = Process | EconomicResource

type EconomicEvent {
  "Defines the process to which this event is an input."
  inputOf: Process

  "Defines the process for which this event is an output."
  outputOf: Process

  ##############################################################################
  # inverse relationships and queries

  track: [ProductionFlowItem!]
  trace: [ProductionFlowItem!]
}

type Process {
  ##############################################################################
  # inverse relationships and queries

  observedInputs(first: Int, after: String, last: Int, before: String): EconomicEventConnection
  observedOutputs(first: Int, after: String, last: Int, before: String): EconomicEventConnection
  unplannedInputs(first: Int, after: String, last: Int, before: String): EconomicEventConnection
  unplannedOutputs(first: Int, after: String, last: Int, before: String): EconomicEventConnection

  trace: [EconomicEvent!]
  track: [EconomicEvent!]
}

##
# API input and output types
##

input EconomicEventCreateParams {
  "(`Process`) Defines the process to which this event is an input."
  inputOf: ID

  "(`Process`) Defines the process for which this event is an output."
  outputOf: ID
}
