##
#
# Result ordering parameters for the Planning module
#
# :TODO: decide on final set, what is here might be overkill and we should start with what is needed by usergroups
#
# @package  ValueFlows GraphQL
# @since    2021-12-12
#
##

input IntentsOrder {
  id: Sort
  name: Sort
  inputOf: Sort
  outputOf: Sort
  provider: Sort
  receiver: Sort
  resourceConformsTo: Sort
  resourceInventoriedAs: Sort
  resourceQuantity: Sort
  effortQuantity: Sort
  availableQuantity: Sort
  hasBeginning: Sort
  hasEnd: Sort
  hasPointInTime: Sort
  due: Sort
  finished: Sort
  atLocation: Sort
}

type Query {
  intents(orderBy: IntentsOrder): IntentConnection!
}
