##
#
# ResourceSpecification module
#
# Provides functionality for classifying and organising EconomicResources.
#
# @depends  measurement.gql
# @package  vf-graphql
# @since    2022-05-27
#
##

"""
Specification of a kind of resource. Could define a material item, service, digital item, currency account, etc.
Used instead of a classification when more information is needed, particularly for recipes.
"""
type ResourceSpecification {
  id: ID!

  "An informal or formal textual identifier for a type of resource. Does not imply uniqueness."
  name: String!

  "The uri to an image relevant to the entity, such as a photo, diagram, etc."
  image: URI

  "References a concept in a common taxonomy or other classification scheme for purposes of categorization or grouping."
  resourceClassifiedAs: [URI!]

  "A textual description or comment."
  note: String

  "The default unit used for the resource itself."
  defaultUnitOfResource: Unit

  "The default unit used for use or work."
  defaultUnitOfEffort: Unit
}

##
# API input and output types
##

input ResourceSpecificationCreateParams {
  "An informal or formal textual identifier for a type of resource. Does not imply uniqueness."
  name: String!

  "The uri to an image relevant to the entity, such as a photo, diagram, etc."
  image: URI

  "References a concept in a common taxonomy or other classification scheme for purposes of categorization or grouping."
  resourceClassifiedAs: [URI!]

  "A textual description or comment."
  note: String

  "(`Unit`) The default unit used for the resource itself."
  defaultUnitOfResource: ID

  "(`Unit`) The default unit used for use or work."
  defaultUnitOfEffort: ID
}

input ResourceSpecificationUpdateParams {
  id: ID!

  "An informal or formal textual identifier for a type of resource. Does not imply uniqueness."
  name: String

  "The uri to an image relevant to the entity, such as a photo, diagram, etc."
  image: URI

  "References a concept in a common taxonomy or other classification scheme for purposes of categorization or grouping."
  resourceClassifiedAs: [URI!]

  "A textual description or comment."
  note: String

  "(`Unit`) The default unit used for the resource itself."
  defaultUnitOfResource: ID

  "(`Unit`) The default unit used for use or work."
  defaultUnitOfEffort: ID
}

type ResourceSpecificationResponse {
  resourceSpecification: ResourceSpecification!
}

type Query {
  resourceSpecification(id: ID!): ResourceSpecification
  resourceSpecifications(start: ID, limit: Int): [ResourceSpecification!]
}

type Mutation {
  createResourceSpecification(resourceSpecification: ResourceSpecificationCreateParams!): ResourceSpecificationResponse!
  updateResourceSpecification(resourceSpecification: ResourceSpecificationUpdateParams!): ResourceSpecificationResponse!
  deleteResourceSpecification(id: ID!): Boolean!
}
